import json
import os
import re
from statistics import pstdev

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


LLM_JUDGE_PROMPT = """You are judging whether a piece of creative writing was likely \
written by a human or generated by an AI language model.

Weigh things like: idea originality, voice consistency, idiosyncratic word choices, \
and whether the phrasing reads as templated or instruction-following versus a distinct \
authorial voice.

Respond with strict JSON only, no other text, in this exact shape:
{"ai_likelihood": <float between 0 and 1, where 1.0 means certainly AI-generated and \
0.0 means certainly human-written>, "rationale": "<one or two sentence explanation>"}

Text to judge:
---
__TEXT__
---"""


def get_llm_signal(text):
    """Signal 1: Groq LLM-as-judge. Returns {"ai_likelihood": float, "rationale": str}."""
    client = _get_client()
    prompt = LLM_JUDGE_PROMPT.replace("__TEXT__", text)
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        temperature=0,
        response_format={"type": "json_object"},
        messages=[
            {"role": "user", "content": prompt},
        ],
    )
    result = json.loads(response.choices[0].message.content)
    ai_likelihood = max(0.0, min(1.0, float(result["ai_likelihood"])))
    return {"ai_likelihood": ai_likelihood, "rationale": result.get("rationale", "")}


# Stock transitional/discourse phrases that instruction-tuned LLMs overuse relative to
# typical creative writing. Matched case-insensitively as substrings.
DISCOURSE_MARKERS = [
    "moreover",
    "furthermore",
    "in conclusion",
    "it is important to note",
    "it is worth noting",
    "overall",
    "additionally",
    "in addition",
    "however",
    "therefore",
    "consequently",
    "as a result",
    "on the other hand",
    "in summary",
    "ultimately",
]


def _clamp(value):
    return max(0.0, min(1.0, value))


def get_stylometric_signal(text):
    """Signal 2: pure-Python stylometric heuristics.

    Returns {"ai_likelihood": float, "features": {...}} where ai_likelihood is the mean
    of three sub-feature scores, each normalized to [0,1] in the "AI-like" direction.
    """
    words = re.findall(r"[a-zA-Z']+", text)
    total_words = len(words)

    # Split into sentences on terminal punctuation; ignore empty fragments.
    sentences = [s for s in re.split(r"[.!?]+", text) if s.strip()]
    sentence_lengths = [len(re.findall(r"[a-zA-Z']+", s)) for s in sentences]

    # Burstiness: low variance in sentence length reads as more AI-like. A population
    # stdev of ~8 words is treated as a typical-human baseline (score -> 0).
    if len(sentence_lengths) >= 2:
        length_stdev = pstdev(sentence_lengths)
    else:
        length_stdev = 0.0
    burstiness_score = _clamp(1 - length_stdev / 8)

    # Lexical repetition: lower type-token ratio (less diverse vocabulary) is more AI-like.
    if total_words > 0:
        ttr = len(set(w.lower() for w in words)) / total_words
    else:
        ttr = 1.0
    repetition_score = _clamp(1 - ttr)

    # Discourse-marker density: more stock transitions per word is more AI-like. Scaled by
    # 40 so that ~1 marker every 40 words approaches the top of the range.
    lower_text = text.lower()
    marker_count = sum(lower_text.count(marker) for marker in DISCOURSE_MARKERS)
    if total_words > 0:
        marker_score = _clamp((marker_count / total_words) * 40)
    else:
        marker_score = 0.0

    # Weighted combination, not a plain mean. Per the blind-spot analysis in
    # planning.md Section 3/10, burstiness and type-token ratio are length-confounded and
    # unreliable on short text, while discourse-marker density is the most robust AI tell.
    # So markers carry half the stylometric weight, the two length-sensitive features a
    # quarter each. (M4 verification finding — see planning.md Section 3.)
    ai_likelihood = 0.5 * marker_score + 0.25 * burstiness_score + 0.25 * repetition_score

    return {
        "ai_likelihood": ai_likelihood,
        "features": {
            "burstiness_score": round(burstiness_score, 4),
            "repetition_score": round(repetition_score, 4),
            "marker_score": round(marker_score, 4),
            "sentence_length_stdev": round(length_stdev, 4),
            "type_token_ratio": round(ttr, 4),
            "marker_count": marker_count,
            "total_words": total_words,
        },
    }


def combine_scores(signal1, signal2):
    """Combine the two signals into a single calibrated confidence score and label.

    combined_score = 0.5 * signal1 + 0.5 * signal2  (planning.md Section 3)
    Thresholds (planning.md Section 4):
        >= 0.70           -> likely_ai
        <= 0.30           -> likely_human
        0.30 < s < 0.70   -> uncertain
    """
    combined_score = 0.5 * signal1["ai_likelihood"] + 0.5 * signal2["ai_likelihood"]
    combined_score = _clamp(combined_score)

    if combined_score >= 0.70:
        attribution = "likely_ai"
    elif combined_score <= 0.30:
        attribution = "likely_human"
    else:
        attribution = "uncertain"

    return {"combined_score": combined_score, "attribution": attribution}
