import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


LLM_JUDGE_PROMPT = """You are judging whether a piece of creative writing was likely \
written by a human or generated by an AI language model.

Weigh things like: idea originality, voice consistency, idiosyncratic word choices, \
and whether the phrasing reads as templated or instruction-following versus a distinct \
authorial voice.

Respond with strict JSON only, no other text, in this exact shape:
{"ai_likelihood": <float between 0 and 1, where 1.0 means certainly AI-generated and \
0.0 means certainly human-written>, "rationale": "<one or two sentence explanation>"}

Text to judge:
---
__TEXT__
---"""


def get_llm_signal(text):
    """Signal 1: Groq LLM-as-judge. Returns {"ai_likelihood": float, "rationale": str}."""
    client = _get_client()
    prompt = LLM_JUDGE_PROMPT.replace("__TEXT__", text)
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        temperature=0,
        response_format={"type": "json_object"},
        messages=[
            {"role": "user", "content": prompt},
        ],
    )
    result = json.loads(response.choices[0].message.content)
    ai_likelihood = max(0.0, min(1.0, float(result["ai_likelihood"])))
    return {"ai_likelihood": ai_likelihood, "rationale": result.get("rationale", "")}
